---
- name: Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed update-cache=yes

- name: Add the node.js PPA for lucid
  action: command add-apt-repository ppa:chris-lea/node.js
  when: ansible_distribution_release == 'trusty'

- name: Install nodejs and npm
  action: apt pkg=nodejs state=installed update-cache=yes
